#!/bin/sh
HISTFILE=$HOME/.config/zsh/history
HISTSIZE=100000
SAVEHIST=100000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
#export PATH=$HOME/.local/share/go/bin:$PATH
#export GOPATH=$HOME/.local/share/go
#export PATH=$HOME/.fnm:$PATH
#export PATH="$PATH:./node_modules/.bin"
#eval "$(fnm env)"
eval "$(zoxide init zsh)"
# eval "`pip completion --zsh`"
export PATH=$HOME/.local/bin/:$HOME/.scripts/:$HOME/.emacs.d/bin/:$HOME/.programs/bin/:$PATH

export VISUAL='nvim'

export _ZO_EXCLUDE_DIRS=$HOME/Data/Phone/Android/data/*
# # >>> conda initialize >>>
# # !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$("$HOME/.miniconda/bin/conda" 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "$HOME/.miniconda/etc/profile.d/conda.sh" ]; then
#         . "$HOME/.miniconda/etc/profile.d/conda.sh"
#     else
#         export PATH="$HOME/.miniconda/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# # <<< conda initialize <<<
