#!/bin/bash

bookmark="$(xclip -o)"
file="$HOME/.local/sync/snippets"

if grep -q "$bookmark" "$file"; then
  notify-send "Oops" "Already bookmarked"
else
  notify-send "Bookmark Added!" "$bookmark is now saved to the snippets."
  echo "$bookmark" >> "$file"
fi
